# Generated by Django 6.0.4 on 2026-04-24 15:39

import cloudinary.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourrierArrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ordre', models.CharField(editable=False, help_text='Généré automatiquement au format MPCID/INS/XXXX', max_length=30, unique=True, verbose_name="Numéro d'ordre")),
                ('date_arrivee', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'arrivée")),
                ('origine', models.CharField(help_text='Ex: BCRG, Ministère des Finances...', max_length=200, verbose_name='Origine')),
                ('reference', models.CharField(help_text='Référence du courrier émetteur', max_length=200, verbose_name='Référence')),
                ('date_envoi', models.DateField(blank=True, null=True, verbose_name="Date d'envoi (Du)")),
                ('objet', models.TextField(help_text='Objet du courrier', verbose_name='Objet')),
                ('scan', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Scan / Pièce jointe')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courriers_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Courrier Arrivé',
                'verbose_name_plural': 'Courriers Arrivés',
                'ordering': ['-date_arrivee', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LigneCirculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonction', models.CharField(choices=[('DG', 'Directeur Général'), ('DGA', 'Directeur Général Adjoint'), ('DIR', 'Le Directeur'), ('SD', 'Le Sous Directeur')], max_length=10, verbose_name='Fonction')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('date_signature', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('annotation', models.TextField(blank=True, default='', verbose_name='Annotation')),
                ('observation', models.TextField(blank=True, default='', verbose_name='Observation')),
                ('courrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_circulation', to='Base.courrierarrive', verbose_name='Courrier')),
            ],
            options={
                'verbose_name': 'Ligne de circulation',
                'verbose_name_plural': 'Lignes de circulation',
                'ordering': ['ordre'],
                'unique_together': {('courrier', 'fonction')},
            },
        ),
    ]
