# Generated by Django 6.0.4 on 2026-04-24 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lignecirculation',
            options={'ordering': ['ordre']},
        ),
        migrations.AlterField(
            model_name='courrierarrive',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='courrierarrive',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courriers_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='courrierarrive',
            name='date_envoi',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'envoi"),
        ),
        migrations.AlterField(
            model_name='courrierarrive',
            name='numero_ordre',
            field=models.CharField(editable=False, max_length=30, unique=True, verbose_name="Numéro d'ordre"),
        ),
        migrations.AlterField(
            model_name='courrierarrive',
            name='objet',
            field=models.TextField(verbose_name='Objet'),
        ),
        migrations.AlterField(
            model_name='courrierarrive',
            name='origine',
            field=models.CharField(max_length=200, verbose_name='Origine'),
        ),
        migrations.AlterField(
            model_name='courrierarrive',
            name='reference',
            field=models.CharField(max_length=200, verbose_name='Référence'),
        ),
        migrations.AlterField(
            model_name='courrierarrive',
            name='scan',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Scan (public_id ou URL Cloudinary)'),
        ),
        migrations.AlterField(
            model_name='courrierarrive',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lignecirculation',
            name='annotation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='lignecirculation',
            name='courrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_circulation', to='Base.courrierarrive'),
        ),
        migrations.AlterField(
            model_name='lignecirculation',
            name='date_signature',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lignecirculation',
            name='fonction',
            field=models.CharField(choices=[('DG', 'Directeur Général'), ('DGA', 'Directeur Général Adjoint'), ('DIR', 'Le Directeur'), ('SD', 'Le Sous Directeur')], max_length=10),
        ),
        migrations.AlterField(
            model_name='lignecirculation',
            name='observation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='lignecirculation',
            name='ordre',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
