# Generated by Django 6.0.4 on 2026-04-26 15:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_alter_lignecirculation_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourrierSortant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sortie', models.CharField(editable=False, help_text='Généré automatiquement au format INS-OUT/XXXX', max_length=30, unique=True, verbose_name='Numéro de sortie')),
                ('origine', models.CharField(help_text='Service ou entité émettrice', max_length=200, verbose_name='Origine')),
                ('objet', models.TextField(verbose_name='Objet')),
                ('destinataire', models.CharField(max_length=200, verbose_name='Nom du destinataire')),
                ('date_sortie', models.DateField(default=django.utils.timezone.now, verbose_name='Date de sortie')),
                ('scan', models.CharField(blank=True, max_length=500, null=True, verbose_name='Scan / Pièce jointe (URL Cloudinary)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courriers_sortants_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Courrier Sortant',
                'verbose_name_plural': 'Courriers Sortants',
                'ordering': ['-date_sortie', '-id'],
            },
        ),
    ]
