# Generated by Django 6.0.4 on 2026-04-26 15:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0003_courriersortant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_archive', models.CharField(editable=False, help_text='Généré automatiquement au format INS-ARC/XXXX', max_length=30, unique=True, verbose_name="Numéro d'archive")),
                ('type_courrier', models.CharField(choices=[('arrive', 'Courrier Arrivé'), ('sortant', 'Courrier Sortant'), ('interne', 'Document Interne')], default='arrive', max_length=20, verbose_name='Type de courrier')),
                ('objet', models.TextField(verbose_name='Objet / Description')),
                ('origine', models.CharField(max_length=200, verbose_name='Origine / Émetteur')),
                ('destinataire', models.CharField(blank=True, default='', max_length=200, verbose_name='Destinataire (si sortant)')),
                ('date_document', models.DateField(default=django.utils.timezone.now, verbose_name='Date du document')),
                ('date_archivage', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'archivage")),
                ('reference_courrier', models.CharField(blank=True, default='', help_text='Ex: MPCID/INS/0001 ou INS-OUT/0001', max_length=50, verbose_name='Référence courrier source')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('archive', 'Archivé'), ('detruit', 'Détruit')], default='archive', max_length=20, verbose_name='Statut')),
                ('observations', models.TextField(blank=True, default='', verbose_name='Observations')),
                ('scan', models.CharField(blank=True, max_length=500, null=True, verbose_name='Scan / Document numérisé (URL Cloudinary)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archives_crees', to=settings.AUTH_USER_MODEL, verbose_name='Archivé par')),
            ],
            options={
                'verbose_name': 'Archive',
                'verbose_name_plural': 'Archives',
                'ordering': ['-date_archivage', '-id'],
            },
        ),
    ]
