# Generated by Django 6.0.4 on 2026-04-29 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0004_archive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Direction',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='DemandeConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_conge', models.CharField(choices=[('annuel', 'Congé annuel'), ('maladie', 'Congé maladie'), ('maternite', 'Congé maternité'), ('sans_solde', 'Congé sans solde'), ('autre', 'Autre')], default='annuel', max_length=20)),
                ('date_debut', models.DateField(verbose_name='Date de début du congé')),
                ('date_fin', models.DateField(verbose_name='Date de fin du congé')),
                ('nombre_jours', models.PositiveIntegerField(editable=False, verbose_name='Nombre de jours')),
                ('motif', models.TextField(blank=True, verbose_name='Motif')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('validee_sup', 'Validée par le supérieur'), ('validee_drh', 'Validée par la DRH'), ('refusee', 'Refusée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('date_valid_sup', models.DateTimeField(blank=True, null=True)),
                ('date_valid_drh', models.DateTimeField(blank=True, null=True)),
                ('commentaire_rh', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valide_par_drh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conges_valides_drh', to=settings.AUTH_USER_MODEL)),
                ('valide_par_sup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conges_valides_sup', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de congé',
                'verbose_name_plural': 'Demandes de congé',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutorisationAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=30, unique=True)),
                ('date_generation', models.DateField(auto_now_add=True)),
                ('pdf_url', models.CharField(blank=True, max_length=500, null=True)),
                ('conge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='autorisation', to='Base.demandeconge')),
            ],
            options={
                'verbose_name': "Autorisation d'absence",
            },
        ),
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, unique=True)),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fonctions', to='Base.direction')),
            ],
            options={
                'verbose_name': 'Fonction',
                'ordering': ['titre'],
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_employe', models.CharField(choices=[('fonctionnaire', 'Fonctionnaire'), ('contractuel', 'Contractuel')], max_length=20, verbose_name="Type d'employé")),
                ('matricule_interne', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Matricule interne')),
                ('matricule_fp', models.CharField(blank=True, max_length=100, null=True, verbose_name='Matricule Fonction Publique')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(max_length=200, verbose_name='Lieu de naissance')),
                ('nationalite', models.CharField(default='Guinéenne', max_length=100, verbose_name='Nationalité')),
                ('adresse', models.CharField(blank=True, max_length=300, verbose_name='Adresse résidentielle')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('diplome', models.CharField(blank=True, max_length=200, verbose_name='Diplôme obtenu')),
                ('diplome_date', models.DateField(blank=True, null=True, verbose_name="Date d'obtention")),
                ('diplome_lieu', models.CharField(blank=True, max_length=200, verbose_name="Lieu d'obtention")),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('salaire', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Salaire de base (GNF)')),
                ('prime', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Prime gouvernementale (GNF)')),
                ('net_a_payer', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='Net à payer (GNF)')),
                ('cnss_id', models.CharField(blank=True, max_length=100, verbose_name='Identifiant CNSS')),
                ('cnss_date_debut', models.DateField(blank=True, null=True, verbose_name='CNSS — Date de début')),
                ('cnss_date_fin', models.DateField(blank=True, null=True, verbose_name='CNSS — Date de fin')),
                ('piece_identite', models.CharField(blank=True, max_length=500, null=True, verbose_name="Pièce d'identité (URL/public_id)")),
                ('rib', models.CharField(blank=True, max_length=500, null=True, verbose_name='RIB (URL/public_id)')),
                ('autres_pieces', models.CharField(blank=True, max_length=500, null=True, verbose_name='Autres pièces jointes')),
                ('photo', models.CharField(blank=True, max_length=500, null=True, verbose_name='Photo (URL/public_id)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel_crees', to=settings.AUTH_USER_MODEL)),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='Base.direction')),
                ('fonction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='Base.fonction')),
            ],
            options={
                'verbose_name': 'Personnel',
                'verbose_name_plural': 'Personnel',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.AddField(
            model_name='demandeconge',
            name='personnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conges', to='Base.personnel'),
        ),
        migrations.CreateModel(
            name='AssuranceMaladie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_carte', models.CharField(blank=True, max_length=100, verbose_name='N° carte assurance')),
                ('date_adhesion', models.DateField(blank=True, null=True, verbose_name="Date d'adhésion")),
                ('date_expiration', models.DateField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('actif', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('personnel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assurance', to='Base.personnel')),
            ],
            options={
                'verbose_name': 'Assurance maladie',
            },
        ),
        migrations.CreateModel(
            name='SoldeConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jours_acquis', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('jours_pris', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('jours_restants', models.DecimalField(decimal_places=1, default=0, editable=False, max_digits=6)),
                ('annee', models.PositiveIntegerField(default=2026)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('personnel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solde_conge', to='Base.personnel')),
            ],
            options={
                'verbose_name': 'Solde de congé',
            },
        ),
    ]
