# """
# Django settings for Server project.

# Generated by 'django-admin startproject' using Django 5.2.5.

# For more information on this file, see
# https://docs.djangoproject.com/en/5.2/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/5.2/ref/settings/
# """

# from pathlib import Path
# import os
# import cloudinary
# import cloudinary.uploader
# import cloudinary.api
# from dotenv import load_dotenv
# import os
# load_dotenv()
# # from dotenv import load_dotenv

# # load_dotenv()

# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent


# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-s9&^32vii1tyxmthd9suveocy&*-2zgyjrnncj$m@cds=z)z=t'

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# ALLOWED_HOSTS = ["*"]


# # Application definition

# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     'Base',
#     'corsheaders',
#     'django_filters', 
#     'cloudinary',
#     'cloudinary_storage',
# ]

# MIDDLEWARE = [
#     'corsheaders.middleware.CorsMiddleware', 
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# ]

# ROOT_URLCONF = 'Server.urls'

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = 'Server.wsgi.application'


# import cloudinary
# cloudinary.config(
#     cloud_name = os.getenv('CLOUDINARY_CLOUD_NAME'),
#     api_key    = os.getenv('CLOUDINARY_API_KEY'),
#     api_secret = os.getenv('CLOUDINARY_API_SECRET'),
#     secure     = True,
# )

# DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# REST_FRAMEWORK = {
#     "DEFAULT_AUTHENTICATION_CLASSES": (
#         "rest_framework_simplejwt.authentication.JWTAuthentication",
#     ),
#     "DEFAULT_PERMISSION_CLASSES": (
#         "rest_framework.permissions.IsAuthenticated",
#     ),
# }

# from datetime import timedelta

# SIMPLE_JWT = {
#     'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
#     'AUTH_HEADER_TYPES': ('Bearer',),
# }
# AUTHENTICATION_BACKENDS = (
#     "django.contrib.auth.backends.ModelBackend",
# )


# CORS_ALLOW_CREDENTIALS = True   # ← OBLIGATOIRE
# CORS_ALLOW_ALL_ORIGINS = False  # ← PAS DE TRUE ici sinon erreur
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:5173",
#     "http://127.0.0.1:5173",
#     "https://inssystems.vercel.app",
  

# ]

# CSRF_TRUSTED_ORIGINS = [
#     "http://localhost:5173",
#     "http://127.0.0.1:5173",
#     "https://inssystems.vercel.app",
 
# ]

# CORS_ALLOW_HEADERS = [
#     'accept',
#     'content-type',
#     'authorization',
#     'x-csrftoken',
#     'x-requested-with',
# ]



# # Database
# # https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASE_URL = os.environ.get("DATABASE_URL")

# if DATABASE_URL:
#     DATABASES = {
#         'default': dj_database_url.config(default=DATABASE_URL, conn_max_age=600)
#     }
# else:
#     DATABASES = {
#         'default': {
#             'ENGINE': 'django.db.backends.mysql',
#             'NAME': 'inssystemsdb',
#             'USER': 'root',
#             'PASSWORD': 'root',
#             'HOST': 'localhost',
#             'PORT': '3306',
#             'ATOMIC_REQUESTS': True, 
#             'OPTIONS': {
#                 'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"
#             }
#         }
#     }



# # Password validation
# # https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# # Internationalization
# # https://docs.djangoproject.com/en/5.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'

# USE_I18N = True

# USE_TZ = True


# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/5.2/howto/static-files/

# STATIC_URL = 'static/'

# # Default primary key field type
# # https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# settings.py
# settings.py
from pathlib import Path
import os
from dotenv import load_dotenv

# ── 1. Charger .env EN PREMIER ───────────────────────────
load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-s9&^32vii1tyxmthd9suveocy&*-2zgyjrnncj$m@cds=z)z=t'
DEBUG      = True
ALLOWED_HOSTS = ["*"]

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'django_filters',
    'cloudinary',
    'cloudinary_storage',
    'Base',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF  = 'Server.urls'
WSGI_APPLICATION = 'Server.wsgi.application'

TEMPLATES = [{
    'BACKEND': 'django.template.backends.django.DjangoTemplates',
    'DIRS': [],
    'APP_DIRS': True,
    'OPTIONS': { 'context_processors': [
        'django.template.context_processors.request',
        'django.contrib.auth.context_processors.auth',
        'django.contrib.messages.context_processors.messages',
    ]},
}]

# ── 2. Cloudinary — UNE SEULE configuration ──────────────
import cloudinary
import cloudinary.uploader
import cloudinary.api

_CLOUD_NAME   = os.getenv('CLOUDINARY_CLOUD_NAME', '')
_API_KEY      = os.getenv('CLOUDINARY_API_KEY', '')
_API_SECRET   = os.getenv('CLOUDINARY_API_SECRET', '')

cloudinary.config(
    cloud_name = _CLOUD_NAME,
    api_key    = _API_KEY,
    api_secret = _API_SECRET,
    secure     = True,
)

# Pour cloudinary_storage (utilisé si DEFAULT_FILE_STORAGE est défini)
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': _CLOUD_NAME,
    'API_KEY':    _API_KEY,
    'API_SECRET': _API_SECRET,
}

# NE PAS définir DEFAULT_FILE_STORAGE — on gère Cloudinary manuellement dans views.py
# DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# Vérification au démarrage
print("\n" + "="*50)
print("🔑 Cloudinary config:")
print(f"   cloud_name : {_CLOUD_NAME or '❌ MANQUANT'}")
print(f"   api_key    : {_API_KEY[:6]+'...' if _API_KEY else '❌ MANQUANT'}")
print(f"   api_secret : {'✅ OK' if _API_SECRET else '❌ MANQUANT'}")
print("="*50 + "\n")

# ── 3. REST Framework ─────────────────────────────────────
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'AUTH_HEADER_TYPES': ('Bearer',),
}

AUTHENTICATION_BACKENDS = ("django.contrib.auth.backends.ModelBackend",)

# ── 4. CORS ───────────────────────────────────────────────
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "https://inssystems.vercel.app",
]
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "https://inssystems.vercel.app",
]
CORS_ALLOW_HEADERS = [
    'accept', 'content-type', 'authorization', 'x-csrftoken', 'x-requested-with',
]

# ── 5. Base de données ────────────────────────────────────
DATABASE_URL = os.environ.get("DATABASE_URL")
if DATABASE_URL:
    import dj_database_url
    DATABASES = {'default': dj_database_url.config(default=DATABASE_URL, conn_max_age=600)}
else:
    DATABASES = {'default': {
        'ENGINE':   'django.db.backends.mysql',
        'NAME':     'inssystemsdb',
        'USER':     'root',
        'PASSWORD': 'root',
        'HOST':     'localhost',
        'PORT':     '3306',
        'ATOMIC_REQUESTS': True,
        'OPTIONS':  {'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"}
    }}

# ── 6. Divers ─────────────────────────────────────────────
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]
LANGUAGE_CODE      = 'fr-fr'
TIME_ZONE          = 'Africa/Conakry'
USE_I18N           = True
USE_TZ             = True
STATIC_URL         = 'static/'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'